-- BigNoteBox UI/OkPhrases.lua
--
-- Shared pool of lore-friendly OK button phrases used by WhatsNew and
-- FeatureList. Add new entries here to have them appear in both windows.
--
-- PUBLIC API:
--   BNB.RandomOkPhrase()  ->  string

local BNB = BigNoteBox

BNB.OK_PHRASES = {
    "For Azeroth!",
    "Light's blessings!",
    "By the Earthmother!",
    "Well met!",
    "Lok'tar!",
    "As you wish, champion",
    "For the king!",
    "By Elune!",
    "The Light guides us",
    "Ishnu-alah!",
    "Zug zug",
    "Stay a while and listen!",
    "Strength and honor!",
    "For Khaz Algar!",
    "Blood and thunder!",
    "By the ancestors!",
    "More dots!",
    "Ready to raid!",
    "By the titans!",
    "Keep your wits about you",
    "May fortune favor you",
    "Stand ready",
    "Let it be done",
    "To the task",
    "Eyes open",
    "On your guard",
    "Another step forward",
    "The path is clear",
    "Safe travels",
    "Walk with honor",
    "The spirits guide you",
    "May your blade stay sharp",
    "Adventure awaits",
    "The journey continues",
    "Destiny calls",
    "Onward, champion",
    "Stand as one",
    "Glory awaits",
    "By starlight",
    "Keep to the path",
    "Fortune guide you",
    "The winds favor you",
    "Steel yourself",
    "Into the unknown",
    "May your aim be true",
    "The world endures",
    "Face the darkness",
    "Forward together",
    "By fire and shadow",
    "Take heart",
    "The way is open",
    "Hold fast",
    "The hunt continues",
    "Courage and wisdom",
    "Answer the call",
    "Fear no evil",
    "The tides turn",
    "Honor the oath",
    "Rise to the challenge",
    "The storm approaches",
    "May the Light protect you",
    "Trust in the elements",
    "The drums of war sound",
    "The earth remembers",
    "Keep faith",
    "Stand your ground",
    "To victory",
    "The battle awaits",
    "Let the forge burn bright",
    "Shadows gather",
    "Press onward",
    "The veil grows thin",
    "Fate favors the bold",
    "Together we endure",
    "Strength through unity",
    "The spirits are restless",
    "Do not falter",
    "Another legend begins",
    "The flame still burns",
    "The mountain stands eternal",
    "May your enemies tremble",
    "The call cannot be ignored",
    "All is as it should be",
    "Step carefully",
    "The hour is at hand",
    "Brace yourself",
    "The skies watch over us",
    "Victory or death",
    "Remain vigilant",
    "The world needs heroes",
    "The elements answer",
    "Your path awaits",
    "Let wisdom guide you",
    "Stand tall",
    "Through hardship, strength",
    "Strike true",
    "May the stars guide you",
    "Darkness cannot prevail",
    "Honor the fallen",
    "The future is unwritten",
    "Answer with courage",
    "Let none stand against you",
    "The fire within burns bright",
    "Champions rise",
    "Guard your spirit",
    "Walk in balance",
    "The dream endures",
    "Take your place",
    "Face what comes",
    "The horizon beckons",
    "The forge is lit",
    "The cycle continues",
    "Stand united",
    "Let the echoes guide you",
    "The winds are changing",
    "Strength in every step",
    "The wilds call",
    "None can stop us",
    "Prepare yourself",
    "The spirits watch",
    "May your legend grow",
    "Another victory awaits",
    "The world turns ever onward",
    "Keep moving forward",
    "The oath remains",
    "Beyond the horizon",
    "Stand firm",
    "Let courage lead",
    "By might and magic",
    "The dawn approaches",
    "All shall be revealed",
    "Rise and endure",
    "The reckoning comes"
}

function BNB.RandomOkPhrase()
    local t = BNB.OK_PHRASES
    return t[math.random(#t)]
end
