-- BigNoteBox Assets/Icons/IconManifest.lua
--
-- The note icons the pickers offer, by category (ALL-238, 2026-10-04). Kept by
-- hand. Every name is a game icon drawn from Interface\Icons\, except the race
-- portraits (Races), which ship with the addon. Each icon here was found on
-- Retail and on Forever by the dev addon's /bnbicons probe; 30 that one client
-- lacks were left out (their old saved paths: BNB.LegacyIconPath, NoteFields.lua).
-- Loaded before NoteConfig.lua.
--   BNB.ICON_CATALOG  = { { key = "books", list = { path, ... } }, ... }
--   BNB.ICON_MANIFEST = every path, flat, in catalog order
--   BNB.ICON_CATEGORY = path -> category key
BigNoteBox = BigNoteBox or {}
local BNB = BigNoteBox

local GAME = "Interface\\Icons\\"
local OWN  = "Interface\\AddOns\\BigNoteBox\\Assets\\Icons\\"

-- Races playable on Forever (Dukul, 2026-10-04): the original eight, by the race
-- word in Achievement_Character_<race>_*, plus Skyborne, a race only Forever has
local FOREVER_RACES = { Human = true, Dwarf = true, Nightelf = true, Gnome = true,
                        Orc = true, Undead = true, Tauren = true, Troll = true }
local FOREVER_ONLY  = { race_skyborne_female = true, race_skyborne_male = true }

-- Whether a race portrait belongs on this client (BNB.IsForever, Init.lua)
local function RaceOnThisClient(name)
    if FOREVER_ONLY[name] then return BNB.IsForever end
    if not BNB.IsForever then return true end
    local race = name:match("^Achievement_Character_(%a+)_")
    return race ~= nil and FOREVER_RACES[race] == true
end

local CATS = {
    { key = "books", names = {
        "INV_Archaeology_80_Witch_Book",
        "INV_Misc_Book_01",
        "INV_Misc_Book_02",
        "INV_Misc_Book_03",
        "INV_Misc_Book_04",
        "INV_Misc_Book_05",
        "INV_Misc_Book_06",
        "INV_Misc_Book_07",
        "INV_Misc_Book_08",
        "INV_Misc_Book_09",
        "INV_Misc_Book_10",
        "INV_Misc_Book_11",
    } },
    { key = "notes", names = {
        "INV_MISC_NOTE_02",
        "INV_MISC_NOTE_06",
        "INV_Misc_NoteBlank1a",
        "INV_Misc_NoteBlank1b",
        "INV_Misc_NoteBlank1c",
        "INV_Misc_NoteBlank2a",
        "INV_Misc_NoteBlank2b",
        "INV_Misc_NoteBlank2c",
        "INV_Misc_NoteFolded1a",
        "INV_Misc_NoteFolded1b",
        "INV_Misc_NoteFolded1c",
        "INV_Misc_NoteFolded1d",
        "INV_Misc_NoteFolded2a",
        "INV_Misc_NoteFolded2b",
        "INV_Misc_NoteFolded2c",
        "INV_Misc_NoteFolded2d",
        "INV_Misc_NoteFolded2e",
        "INV_Misc_NoteFolded2f",
        "INV_Misc_NoteFolded3a",
        "INV_Misc_NoteFolded3b",
        "INV_Misc_NoteFolded3c",
        "INV_Misc_NoteFolded3d",
        "INV_Misc_NoteFolded3e",
        "INV_Misc_NoteFolded3f",
        "INV_Misc_NotePicture1a",
        "INV_Misc_NotePicture1b",
        "INV_Misc_NotePicture1c",
        "INV_Misc_NotePicture2a",
        "INV_Misc_NotePicture2b",
        "INV_Misc_NotePicture2c",
        "INV_Misc_NoteScript1a",
        "INV_Misc_NoteScript1b",
        "INV_Misc_NoteScript1c",
        "INV_Misc_NoteScript1d",
        "INV_Misc_NoteScript1e",
        "INV_Misc_NoteScript2a",
        "INV_Misc_NoteScript2b",
        "INV_Misc_NoteScript2c",
        "INV_Misc_NoteScript2d",
        "INV_Misc_NoteScript2e",
        "INV_Misc_Note_01",
        "INV_Misc_Note_03",
        "INV_Misc_Note_04",
        "INV_Misc_Note_05",
    } },
    { key = "classes", names = {
        "ClassIcon_DeathKnight",
        "ClassIcon_DemonHunter",
        "ClassIcon_Druid",
        "ClassIcon_Evoker",
        "ClassIcon_Evoker_Augmentation",
        "ClassIcon_Evoker_Devastation",
        "ClassIcon_Evoker_Preservation",
        "ClassIcon_Hunter",
        "ClassIcon_Mage",
        "ClassIcon_Monk",
        "ClassIcon_Paladin",
        "ClassIcon_Priest",
        "ClassIcon_Rogue",
        "ClassIcon_Shaman",
        "ClassIcon_Warlock",
        "ClassIcon_Warrior",
    } },
    { key = "factions", names = {
        "Achievement_DoubleJeopardyHorde",
        "INV_Tabard_BattlePVPS4_horde",
        "INV_Tabard_HordeWarEffort",
        "INV_ViciousFlyingNerubian2_Horde",
        "Inv_Misc_Tournaments_Symbol_Human",
        "Inv_Misc_Tournaments_Tabard_Human",
        "Inv_Misc_Tournaments_banner_Human",
        "UI_AllianceIcon",
        "UI_Alliance_7LegionMedal",
        "UI_HordeIcon",
        "UI_Horde_HonorboundMedal",
    } },
    { key = "instances", names = {
        "Achievement_Dungeon_AtalDazar",
        "Achievement_Dungeon_BrackenhideHollow",
        "Achievement_Dungeon_CentaurPlains",
        "Achievement_Dungeon_ClassicDungeonMaster",
        "Achievement_Dungeon_ClassicRaider",
        "Achievement_Dungeon_FirelandsRaid",
        "Achievement_Dungeon_Freehold",
        "Achievement_Dungeon_HallsofInfusion",
        "Achievement_Dungeon_Icecrown_ForgeofSouls",
        "Achievement_Dungeon_Icecrown_FrostwingHalls",
        "Achievement_Dungeon_Icecrown_HallsofReflection",
        "Achievement_Dungeon_Icecrown_IcecrownEntrance",
        "Achievement_Dungeon_KingsRest",
        "Achievement_Dungeon_LifePools",
        "Achievement_Dungeon_Neltharus",
        "Achievement_Dungeon_SanguineDepths",
        "Achievement_Dungeon_ShrineOfTheStorm",
        "Achievement_Dungeon_SkycapnKragg",
        "Achievement_Dungeon_Skywall",
        "Achievement_Dungeon_TempleOfSethraliss",
        "Achievement_Dungeon_UlduarRaid_Misc_03",
        "Achievement_Dungeon_Underrot",
        "Achievement_Dungeon_UpperBlackrockSpire",
        "Achievement_Dungeon_WaycrestMannor",
        "Achievement_Raid_ArgusRaid",
        "Achievement_Raid_ForgottenDepths",
        "Achievement_Raid_Hall_Of_Flesh",
        "Achievement_Raid_Karazhan",
        "Achievement_Raid_MantidRaid01",
        "Achievement_Raid_SecondHalfMogu",
        "Achievement_Raid_SoO_Garrosh_Compound_Half1",
        "Achievement_Raid_SoO_Garrosh_Compound_Half2",
        "Achievement_Raid_SoO_Orgrimmar_outdoors",
        "Achievement_Raid_SoO_Ruined_Vale",
        "Achievement_Raid_TorghastRaid",
        "Achievement_Raid_TrialOfValor",
        "INV_Achievement_Dungeon_Dawnbreaker",
        "INV_Achievement_Dungeon_PrioryoftheSacredFlame",
        "INV_Achievement_Dungeon_Stonevault",
        "INV_Achievement_Raid_Nerubar",
        "achievement_dungeon_HallsofValor",
        "achievement_dungeon_MawofSouls",
        "achievement_dungeon_NeltharionsLair",
        "achievement_dungeon_VaultoftheWardens",
    } },
    { key = "professions", names = {
        "Achievement_Profession_ChefHat",
        "Achievement_Profession_Fishing_JourneymanFisher",
        "Achievement_Profession_Fishing_OutlandAngler",
        "INV_10_Inscription2_RepContracts_TRADE_ARCHAEOLOGY_APEXISSCROLL_Uprez",
        "INV_11_Cooking_Profession_Feast_Table01",
        "INV_Misc_Profession_Book_Alchemy",
        "INV_Misc_Profession_Book_Blacksmithing",
        "INV_Misc_Profession_Book_Cooking",
        "INV_Misc_Profession_Book_Enchanting",
        "INV_Misc_Profession_Book_Engineering",
        "INV_Misc_Profession_Book_Fishing",
        "INV_Misc_Profession_Book_Herbalism",
        "INV_Misc_Profession_Book_Inscription",
        "INV_Misc_Profession_Book_Jewelcrafting",
        "INV_Misc_Profession_Book_Leatherworking",
        "INV_Misc_Profession_Book_Mining",
        "INV_Misc_Profession_Book_Skinning",
        "INV_Misc_Profession_Book_Tailoring",
        "INV_Trade_Alchemy_DPotion_C1A",
        "TRADE_ARCHAEOLOGY",
        "TRADE_ARCHAEOLOGY_CANDLESTUB",
        "TRADE_ARCHAEOLOGY_CHESTOFTINYGLASSANIMALS",
        "TRADE_ARCHAEOLOGY_DWARF_ARTIFACTFRAGMENT",
        "TRADE_ARCHAEOLOGY_DWARF_RUNESTONE",
        "TRADE_ARCHAEOLOGY_GOLDCHAMBERPOT",
        "TRADE_ARCHAEOLOGY_HIGHBORNE_SCROLL",
        "TRADE_ARCHAEOLOGY_ULDUMCANOPICJAR",
        "Trade_Alchemy",
        "Trade_Alchemy_DPotion_A13",
        "Trade_Alchemy_DPotion_A23",
        "Trade_Alchemy_DPotion_A25",
        "Trade_Alchemy_DPotion_B10",
        "Trade_Alchemy_DPotion_C27",
        "Trade_Alchemy_DPotion_E2",
        "Trade_Alchemy_GhostIronRodRuned",
        "Trade_Alchemy_PotionA4",
        "Trade_Archaeology_Aqir_hieroglyphic",
        "Trade_Archaeology_HighborneSoulMirror",
        "Trade_Archaeology_Troll_VoodooDoll",
        "Trade_BlackSmithing",
        "Trade_Cooking_2",
        "Trade_Enchanting_LargeEtherealShard",
        "Trade_Enchanting_SmallEtherealShard",
        "Trade_Engineering",
        "Trade_Engraving",
        "Trade_Fishing",
        "Trade_Herbalism",
        "Trade_LeatherWorking",
        "Trade_Mining",
        "Trade_Tailoring",
        "UI_Profession_Alchemy",
        "UI_Profession_Blacksmithing",
        "UI_Profession_Cooking",
        "UI_Profession_Enchanting",
        "UI_Profession_Engineering",
        "UI_Profession_Fishing",
        "UI_Profession_Herbalism",
        "UI_Profession_Inscription",
        "UI_Profession_Jewelcrafting",
        "UI_Profession_Leatherworking",
        "UI_Profession_Mining",
        "UI_Profession_Skinning",
        "UI_Profession_Tailoring",
    } },
    -- Each client lists only its own races (RaceOnThisClient above)
    { key = "races", own = "Races", races = true, names = {
        "Achievement_Character_Bloodelf_Female",
        "Achievement_Character_Bloodelf_Male",
        "Achievement_Character_Draenei_Female",
        "Achievement_Character_Draenei_Male",
        "Achievement_Character_Dwarf_Female",
        "Achievement_Character_Dwarf_Male",
        "Achievement_Character_Gnome_Female",
        "Achievement_Character_Gnome_Male",
        "Achievement_Character_Human_Female",
        "Achievement_Character_Human_Male",
        "Achievement_Character_Nightelf_Female",
        "Achievement_Character_Nightelf_Male",
        "Achievement_Character_Orc_Female",
        "Achievement_Character_Orc_Male",
        "Achievement_Character_Pandaren_Female",
        "Achievement_Character_Tauren_Female",
        "Achievement_Character_Tauren_Male",
        "Achievement_Character_Troll_Female",
        "Achievement_Character_Troll_Male",
        "Achievement_Character_Undead_Female",
        "Achievement_Character_Undead_Male",
        "achievement_FemaleGoblinhead",
        "achievement_Goblinhead",
        "race_darkirondwarf_female",
        "race_darkirondwarf_male",
        "race_dracthyr_female",
        "race_dracthyr_male",
        "race_earthendwarf_female",
        "race_earthendwarf_male",
        "race_goblin_female",
        "race_goblin_male",
        "race_harronir_female",
        "race_harronir_male",
        "race_highmountaintauren_female",
        "race_highmountaintauren_male",
        "race_kultiran_female",
        "race_kultiran_male",
        "race_lightforgeddraenei_female",
        "race_lightforgeddraenei_male",
        "race_magharorc_female",
        "race_magharorc_male",
        "race_mechagnome_female",
        "race_mechagnome_male",
        "race_nightborne_female",
        "race_nightborne_male",
        "race_pandaren_female",
        "race_pandaren_male",
        "race_vulpera_female",
        "race_vulpera_male",
        "race_worgen_female",
        "race_worgen_male",
        "race_zandalaritroll_female",
        "race_zandalaritroll_male",
        "race_voidelf_female",
        "race_voidelf_male",
        "race_skyborne_female",
        "race_skyborne_male",
    } },
    { key = "random", names = {
        "Ability_Creature_Amber_02",
        "Ability_Creature_Cursed_02",
        "INV_GnomeToy",
        "INV_Misc_Bone_HumanSkull_02",
    } },
    { key = "storage", names = {
        "Battleground_Strongbox_Gold_Horde",
    } },
    { key = "zones", names = {
        "Achievement_Zone_AlteracMountains_01",
        "Achievement_Zone_ArathiHighlands_01",
        "Achievement_Zone_Ashenvale_01",
        "Achievement_Zone_Ashran",
        "Achievement_Zone_AzjKahet",
        "Achievement_Zone_Azshara_01",
        "Achievement_Zone_AzureSpan",
        "Achievement_Zone_AzuremystIsle_01",
        "Achievement_Zone_Badlands_01",
        "Achievement_Zone_Barrens_01",
        "Achievement_Zone_Blackrock_01",
        "Achievement_Zone_BladesEdgeMtns_01",
        "Achievement_Zone_BlastedLands_01",
        "Achievement_Zone_BloodmystIsle_01",
        "Achievement_Zone_BoreanTundra_01",
        "Achievement_Zone_BoreanTundra_02",
        "Achievement_Zone_BoreanTundra_03",
        "Achievement_Zone_BrokenShore",
        "Achievement_Zone_BurningSteppes_01",
        "Achievement_Zone_Cataclysm",
        "Achievement_Zone_Cataclysmgreen",
        "Achievement_Zone_CrystalSong_01",
        "Achievement_Zone_Darkshore_01",
        "Achievement_Zone_Darnassus",
        "Achievement_Zone_DeadwindPass",
        "Achievement_Zone_DeepHolm",
        "Achievement_Zone_Desolace",
        "Achievement_Zone_Draenor_01",
        "Achievement_Zone_DragonBlight_01",
        "Achievement_Zone_DragonBlight_02",
        "Achievement_Zone_Durotar",
        "Achievement_Zone_Duskwood",
        "Achievement_Zone_DustwallowMarsh",
        "Achievement_Zone_EasternKingdoms_01",
        "Achievement_Zone_EasternPlaguelands",
        "Achievement_Zone_EversongWoods",
        "Achievement_Zone_Firelands",
        "Achievement_Zone_ForbiddenReach",
        "Achievement_Zone_Frostfire",
        "Achievement_Zone_Ghostlands",
        "Achievement_Zone_HellfirePeninsula_01",
        "Achievement_Zone_HillsbradFoothills",
        "Achievement_Zone_Hinterlands_01",
        "Achievement_Zone_LochModan",
        "Achievement_Zone_Mulgore_01",
        "Achievement_Zone_Nagrand_01",
        "Achievement_Zone_Nagrand_02",
        "Achievement_Zone_Netherstorm_01",
        "Achievement_Zone_Newshadowmoonvalley",
        "Achievement_Zone_Northrend_01",
        "Achievement_Zone_OhnAhranPlains",
        "Achievement_Zone_Stranglethorn_01",
        "Achievement_Zone_SwampSorrows_01",
        "Achievement_Zone_Talador",
        "Achievement_Zone_TirisfalGlades_01",
        "Achievement_Zone_TwilightHighlands",
        "SPELL_ARCANE_TELEPORTHALLOFTHEGUARDIAN",
        "Spell_Arcane_TeleportDalaran",
        "Spell_Arcane_TeleportDalaranBrokenIsles",
        "Spell_Arcane_TeleportDalaranCrater",
        "Spell_Arcane_TeleportDarnassus",
        "Spell_Arcane_TeleportExodar",
        "Spell_Arcane_TeleportIronForge",
        "Spell_Arcane_TeleportMoonglade",
        "Spell_Arcane_TeleportOrgrimmar",
        "Spell_Arcane_TeleportOribos",
        "Spell_Arcane_TeleportShattrath",
        "Spell_Arcane_TeleportSilvermoon",
        "Spell_Arcane_TeleportStonard",
        "Spell_Arcane_TeleportStormShield",
        "Spell_Arcane_TeleportStormWind",
        "Spell_Arcane_TeleportTheramore",
        "Spell_Arcane_TeleportThunderBluff",
        "Spell_Arcane_TeleportTolBarad",
        "Spell_Arcane_TeleportUnderCity",
        "Spell_Arcane_TeleportValdrakken",
        "Spell_Arcane_TeleportWarSpear",
    } },
}

BNB.ICON_CATALOG, BNB.ICON_MANIFEST, BNB.ICON_CATEGORY = {}, {}, {}
for _, c in ipairs(CATS) do
    local base = c.own and (OWN .. c.own .. "\\") or GAME
    local list = {}
    for _, name in ipairs(c.names) do
        if not c.races or RaceOnThisClient(name) then
            local path = base .. name
            list[#list + 1] = path
            BNB.ICON_MANIFEST[#BNB.ICON_MANIFEST + 1] = path
            BNB.ICON_CATEGORY[path] = c.key
        end
    end
    BNB.ICON_CATALOG[#BNB.ICON_CATALOG + 1] = { key = c.key, list = list }
end

-- The icons of one category, e.g. BNB.IconsIn("notes") (empty table if none)
function BNB.IconsIn(key)
    for _, c in ipairs(BNB.ICON_CATALOG) do
        if c.key == key then return c.list end
    end
    return {}
end
